service: trenduk
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
custom:
  pythonRequirements:
    dockerizePip: true
package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
functions:
  fan-out:
    handler: handler.fan_out
plugins:
  - serverless-python-requirements
