import { Flex, Grid } from "@chakra-ui/react";
import Head from "next/head";
import { ChildStats } from "../components/ChildStats";
import { Goban } from "../components/Goban";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex>
        <Goban size={500} />

        <Grid templateColumns="repeat(2, 4fr)" gap={6}>
          {Array.from(Array(5).keys()).map((_) => (
            <ChildStats />
          ))}
        </Grid>
      </Flex>
    </div>
  );
}
